if(EXISTS "/Users/dong9/SPAECIES/tests/tests_tests-b12d07c.cmake")
  include("/Users/dong9/SPAECIES/tests/tests_tests-b12d07c.cmake")
else()
  add_test(tests_NOT_BUILT-b12d07c tests_NOT_BUILT-b12d07c)
endif()
