# [Integrator settings]
order       = 2
dt          = 1.6384
# dt_partition_1 = 0.0
# dt_partition_2 = 1.e99   
type        = implicit
final_time  = 300.0
rel_tol     = 1.e-15
postprocess = false
use_lookup  = true
cfl_substep = true

# [Save settings] 
steps    = -1
# filename = /home/dong9/postprocessing-SPAECIES/results/final-runs-nov7/reference_solutions/rainshaft_reference_regularized_tf300_qsmall1e-18_epsilonqsat1e-10_abstol0_order3_reltol1e-15.nc
filename = test.nc 

# [Initial conditions] 
ic_file   = /home/dong9/SPAECIES-input-data/random_rainshaft_samples_12mo.nc
num_cases = 1
case_idx  = 193

# [Process settings]
nudging = false
regularize_qsat = true  
regularize_lambdar = true 
qsmall = 1.e-18
epsilon_qsat_fac = 1.e-10
