# [Integrator settings]
order       = 2
dt          = 1.6
dt_fast     =    
type        = implicit
final_time  = 300.0
rel_tol     = 1.e-10
postprocess = false 
use_lookup  = true

# [Save settings] 
steps    = -1
filename = test.nc

# [Initial conditions] 
ic_file   = /home/dong9/SPAECIES-final-version-for-paper/data/random_rainshaft_samples_12mo.nc
num_cases = -1
case_idx  = 

# [Process settings]
nudging = true
regularize_qsat = true
qsmall = 1.e-12
epsilon_qsat_fac = 0.25