# [Integrator settings]
order       = 3
dt          = 0.0
dt_fast     =    
type        = explicit
final_time  = 300.0
rel_tol     = 1.e-13
postprocess = false 
use_lookup  = false

# [Save settings] 
steps    = -1
filename = reference.nc

# [Initial conditions] 
ic_file   = /home/dong9/SPAECIES-final-version-for-paper/data/random_rainshaft_samples_12mo.nc
num_cases = -1
case_idx  = 

# [Process settings]
nudging = false
regularize_qsat = false
qsmall = 1.e-14
epsilon_qsat_fac = 1.e-5